/*  This is mada by Yanran    
 *
 *  功能：鲁塔比斯 - 被封印的世界树
 *
 *  @Author Yanran
 */
        player.setInGameDirectionMode(true, false, false, false);
//player.setStandAloneMode(true);
player.setInGameCurNodeEventEnd(true);
player.setVansheeMode(true);
player.spawnTempNpc(1064028, 840, 435);
player.setNpcSpecialAction(1064028, "summon", 0, false);
//npc.setDelay(1000);
//player.setForcedInput(0);
//player.showPlayerEffectPlay("Effect/BasicEff.img/dragonBlink", 1, 0, 5, true, 0, false, 0);
player.showPlayerEffectPlay("Effect/BasicEff.img/Teleport", 0, 0, 5, true, 0, false, 0);
player.setInGameCurNodeEventEnd(true);
player.setVansheeMode(false);
//npc.setDelay(500);
npc.sayNextSNoEsc("这是什么地方……？");
//player.setForcedInput(2);
//npc.setDelay(4000);
//player.setForcedInput(0);
npc.setCameraMove(false, 400, 600, 443);
npc.sayNextNoEsc("愚蠢的人！为什么要反抗#r“那个人”#k的意志！", 1064017, false);
npc.sayNextSNoEsc("你，你是谁？！");
player.setNpcSpecialAction(1064028, "appearance", 0, true);
//npc.setDelay(5000);
player.showNpcEffectPlay(1064028, "Effect/Direction11.img/bellum/appearance", 1850, 0, 0, true, 0, false, 0);
//npc.setDelay(1700);
player.spawnTempNpc(1064017, 840, 435);
player.setNpcSpecialAction(1064017, "summon", 0, false);
player.destroyTempNpc(1064028);
//npc.setDelay(3000);
npc.sayNextNoEsc("我是侍奉那位#r“伟大的人”#k的封印守护者#b贝伦#k。愚蠢的人，你为什么要到这里来，破坏#r“那个人”#k的心情？", 1064017, false);
npc.sayNextSNoEsc("封印守护者？将世界树封印起来的人是你吗？");
npc.sayNextNoEsc("封印是#r“那个人”#k设下的。我只是按照#r“那个人”#k的命令，在这里守护护封印。", 1064017, false);
npc.sayNextSNoEsc("#r“那个人”#k是指一只眼睛戴着眼罩的那个魔族吗？");
npc.sayNextNoEsc("闭嘴！那个人可不是你能随便挂在嘴上的！在那位#r“伟大的人”#k的力量面前，你就像是一粒渺小的灰尘。总有一天，你也会跪在#r“那个人”#k的面前！", 1064017, false);
npc.sayNextSNoEsc("我不想和他战斗。和他一样都是魔族的恶魔猎手现在也成了我们的同伴。所以你们也应该和我们……");
npc.sayNextNoEsc("肮脏的背叛者竟敢怂恿我们背叛#r“那个人”#k，看来你是活得不耐烦了！", 1064017, false);
player.showPlayerEffectPlay("Effect/Direction11.img/effect/stone/0", 200, -670, 0, true, 0, false, 0);
//npc.setDelay(200);
player.showPlayerEffectPlay("Effect/Direction11.img/effect/stone/0", 1000, -20, 0, true, 0, false, 0);
//npc.setDelay(300);
player.showPlayerEffectPlay("Effect/Direction11.img/effect/stone/0", 5000, -150, 0, true, 0, false, 0);
//npc.setDelay(250);
player.showPlayerEffectPlay("Effect/Direction11.img/effect/stone/0", 1000, -600, 0, true, 0, false, 0);
//npc.setDelay(400);
player.showPlayerEffectPlay("Effect/Direction11.img/effect/stone/0", 2400, 220, 0, true, 0, false, 0);
//npc.setDelay(300);
player.showPlayerEffectPlay("Effect/Direction11.img/effect/stone/0", 1300, 400, 0, true, 0, false, 0);
//npc.setDelay(3000);
npc.sayNextSNoEsc("看来光靠说话行不通。那就只能打败你，然后再获取情报了！");
npc.sayNextNoEsc("凭你也想打败我？那就试试看吧！", 1064017, false);
player.setNpcSpecialAction(1064017, "attack", 0, false);
//npc.setDelay(2500);
//npc.setDelay(900);
player.showPlayerEffectPlay("Effect/Direction11.img/effect/stone/0", 1300, 400, 0, true, 0, false, 0);
player.showPlayerEffectPlay("Effect/Direction11.img/effect/skill/fire", 3000, -40, -25, true, 0, false, 0);
//player.setForcedInput(0);
player.setForcedAction(4, 6000);
//npc.getDirectionInfo(0,222,50000);
npc.sayNextSNoEsc("............");
player.showReservedEffect("Effect/Direction11.img/rootabyssQuest/Scene1");
npc.sayNextNoEsc("这么点程度就不行了吗？现在你知道自己有多无能了吧？", 1064017, false);
player.showReservedEffect("Effect/Direction11.img/rootabyssQuest/Scene1");
npc.sayNextNoEsc("除了我之外，这里还有三个封印守护者。要想解开世界树的封印，必须把我们全部打倒才行。但是以你的力量，估计连一个都无法打倒。", 1064017, false);
player.showReservedEffect("Effect/Direction11.img/rootabyssQuest/Scene1");
npc.sayNextNoEsc("现在你知道你自己是多么可悲的存在了！？这次暂且饶过你这卑贱的生命，别再踏入此处半步，我的仁慈是有限度的。", 1064017, false);
player.showReservedEffect("Effect/Direction11.img/rootabyssQuest/Scene1");
//npc.setDelay(1000);
player.showReservedEffect("Effect/Direction11.img/rootabyssQuest/Scene1");
//player.setForcedInput(0);
player.setVansheeMode(true);
player.showPlayerEffectPlay("Effect/BasicEff.img/dragonBlink", 0, 0, 5, true, 0, false, 0);
//npc.setDelay(1500);
player.showPlayerEffectPlay("Effect/BasicEff.img/Teleport", 0, 0, 5, true, 0, false, 0);
player.changeMap(910700200, 0);
player.setInGameDirectionMode(false, false, false, false);
//player.setStandAloneMode(false);
player.setVansheeMode(false);
player.startQuest(30006, 0);